### ISSUE TITLE
Code cleaning - TODO list 

### ISSUE THREAD

**Issue by duembgen** [LCAV/continuous-localization#54]
- [x] Approve pull request
- [x] Create release for paper 
- [x] Put all plots into one notebook
- [x] Find out which functions are unused with some program
- [x] Clean  documents / notebooks
- [x] Clear some unwanted folders etc.
- [ ] Go through other issues and decide what to do with them
- [ ] Go through "TODOs" in code and clear them / fix them. 
- [x] Decide what to do with `get_full_matrix` and `get_C_constraints` 
- [x] Delete algorithms which we do not use / need anymore

*Can make the repo public from here on* 

- [ ] Decide if we want to have a (basic) documentation
- [x] See if we want to add important images to GenerateAllFigures or README. 
- [ ] Good practice with imports of multiple modules at once
- [ ] Add uniform headers for modules and notebooks
